networks:
  cassandra:
    driver: bridge
volumes:
  cas1:
  cas2:
  cas3:
services:
  cas1:
    image: cassandra:latest
    networks:
      - cassandra
    ports:
      - "9042:9042"
    environment: &env
      - CASSANDRA_SEEDS=cas1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
    volumes:
      - cas1:/var/lib/cassandra
    healthcheck: &health
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
  cas2:
    image: cassandra:latest
    networks:
      - cassandra
    ports:
      - "9043:9042"
    environment: *env
    volumes:
      - cas2:/var/lib/cassandra
    depends_on:
      cas1:
        condition: service_healthy
    healthcheck: *health
  cas3:
    image: cassandra:latest
    networks:
      - cassandra
    ports:
      - "9044:9042"
    environment: *env
    volumes:
      - cas3:/var/lib/cassandra
    depends_on:
      cas2:
        condition: service_healthy
    healthcheck: *health
