networks:
  cassandra:
  postgres:
    driver: bridge
services:
  cassandra1:
    image: cassandra:latest
    networks:
      - cassandra
    ports:
      - "9042:9042"
    environment: &environment
      CASSANDRA_SEEDS: "cassandra1,cassandra2"
      CASSANDRA_CLUSTER_NAME: LibraryCluster
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
  cassandra2:
    image: cassandra:latest
    hostname: cassandra2
    networks:
      - cassandra
    ports:
      - "9043:9042"
    environment: *environment
    depends_on:
      cassandra1:
        condition: service_started
  cassandra3:
    image: cassandra:latest
    networks:
      - cassandra
    ports:
      - "9044:9042"
    environment: *environment
    depends_on:
      cassandra2:
        condition: service_started
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      db:
        condition: service_started
