[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.0"
<<<<<<< HEAD
numpy = "^1.26.4"
||||||| parent of 03bfb90 (feat(api) add db seeding for cassandra)
psycopg2-binary = "^2.9.9"
=======
cassandra-driver = "^3.29.1"
>>>>>>> 03bfb90 (feat(api) add db seeding for cassandra)


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
